version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
